Tests impl
LazyKeru/SmellsFishy pull request #4
Opened 2022-03-12 18:47 UTC by EloiGG

2022-03-12 18:48 UTC, EloiGG commented
keep my gitignore, it ignores all visual studio files, including my projects

2022-03-13 13:10 UTC, LazyKeru reviewed
".vs/SmellsFishy/v17/.suo" and ".vs/slnx.sqlite" are not necessary ? Could be deleted in the near future

2022-03-13 13:17 UTC, LazyKeru requested changes
Need to be up to date with the rest of the projecct

2022-03-13 13:17 UTC, LazyKeru commented on CppProperties.json
> +{
Do we need this file ? As not everyone in the project uses Visual Studio

2022-03-13 13:17 UTC, LazyKeru commented on src/test.cpp
> +}
Nicely done, we can then add it into a workflow

2022-03-13 13:17 UTC, LazyKeru commented on src/io/io.cpp
>  {
This file was renamed in a previous change

2022-03-13 14:00 UTC, LazyKeru commented
Fixed merge conflict and cleaned the directory. The new working branch: [feat-test-function](https://github.com/LazyKeru/SmellsFishy/tree/feat-test-function)

2022-03-13 14:00 UTC, closed without merging